DEFINES += -DDATA_DIR=\"/usr/local/share/dolphin-emu/\"
DEFINES += -DUSE_MEMORYWATCHER=1
DEFINES += -D_ARCH_64=1
DEFINES += -D_DEFAULT_SOURCE
DEFINES += -D_FILE_OFFSET_BITS=64
DEFINES += -D_LARGEFILE_SOURCE
DEFINES += -D_M_X86=1
DEFINES += -D_M_X86_64=1
#DEFINES += -DHAVE_ALSA=1
#DEFINES += -DHAVE_BLUEZ=1
#DEFINES += -DHAVE_LIBEVDEV=1
#DEFINES += -DHAVE_LIBUDEV=1
#DEFINES += -DUSE_PIPES=1


C_DEFINES += -DHAS_FCNTL=1
C_DEFINES += -DHAS_GETADDRINFO=1
C_DEFINES += -DHAS_GETHOSTBYADDR_R=1
C_DEFINES += -DHAS_GETHOSTBYNAME_R=1
C_DEFINES += -DHAS_GETNAMEINFO=1
C_DEFINES += -DHAS_INET_NTOP=1
C_DEFINES += -DHAS_INET_PTON=1
C_DEFINES += -DHAS_MSGHDR_FLAGS=1
C_DEFINES += -DHAS_POLL=1
C_DEFINES += -DHAS_SOCKLEN_T=1
C_DEFINES += -DHAVE_AO=1
C_DEFINES += -DHAVE_LIBAV
C_DEFINES += -DHAVE_OPENAL=1
C_DEFINES += -DHAVE_PORTAUDIO=1
C_DEFINES += -DHAVE_PULSEAUDIO=1
C_DEFINES += -DHAVE_X11=1
C_DEFINES += -DHAVE_XRANDR=1


CXX_DEFINES += -D__STDC_CONSTANT_MACROS
CXX_DEFINES += -DUSE_HEADLESS
CXX_DEFINES += -DUSE_EGL=1
#CXX_DEFINES += -DHAVE_HIDAPI=1
#CXX_DEFINES += -DUSE_UPNP
#CXX_DEFINES += -D__LIBUSB__
#CXX_DEFINES += -D__STDC_LIMIT_MACROS

#not needed:
#CXX_DEFINES += -DHAVE_X11=1
#CXX_DEFINES += -DHAVE_XRANDR=1
#CXX_DEFINES += -DSFML_STATIC
#CXX_DEFINES += -D__WXGTK__

#no effect:
#DEFINES += -DUSE_ANALYTICS=1
