CXX_DEFINES += -DDATA_DIR=\"/usr/local/share/dolphin-emu/\"
#CXX_DEFINES += -DHAVE_ALSA=1

#CXX_DEFINES += -DHAVE_BLUEZ=1
#CXX_DEFINES += -DHAVE_HIDAPI=1
#CXX_DEFINES += -DHAVE_LIBEVDEV=1
#CXX_DEFINES += -DHAVE_LIBUDEV=1

CXX_DEFINES += -DUSE_MEMORYWATCHER=1

#CXX_DEFINES += -DUSE_PIPES=1

#CXX_DEFINES += -DUSE_UPNP
CXX_DEFINES += -D_ARCH_64=1
CXX_DEFINES += -D_DEFAULT_SOURCE
CXX_DEFINES += -D_FILE_OFFSET_BITS=64
CXX_DEFINES += -D_LARGEFILE_SOURCE
CXX_DEFINES += -D_M_X86=1
CXX_DEFINES += -D_M_X86_64=1
#CXX_DEFINES += -D__LIBUSB__
CXX_DEFINES += -D__STDC_CONSTANT_MACROS
CXX_DEFINES += -D__STDC_LIMIT_MACROS


CXX_DEFINES += -DUSE_HEADLESS
CXX_DEFINES += -DUSE_EGL=1

#not needed:
#CXX_DEFINES += -DHAVE_X11=1
#CXX_DEFINES += -DHAVE_XRANDR=1
#CXX_DEFINES += -DSFML_STATIC
#CXX_DEFINES += -D__WXGTK__

#no effect:
#CXX_DEFINES += -DUSE_ANALYTICS=1
