
DEFINES += -D_ARCH_64=1
DEFINES += -D_DEFAULT_SOURCE
DEFINES += -D_FILE_OFFSET_BITS=64
DEFINES += -D_LARGEFILE_SOURCE
DEFINES += -D_M_X86=1
DEFINES += -D_M_X86_64=1
#DEFINES += -DUSE_MEMORYWATCHER=1
#DEFINES += -DHAVE_BLUEZ=1
#DEFINES += -DHAVE_LIBEVDEV=1
#DEFINES += -DHAVE_LIBUDEV=1
#DEFINES += -DUSE_PIPES=1
#DEFINES += -DUSE_ANALYTICS=1

CDEFINES += -DHAS_FCNTL=1
CDEFINES += -DHAS_GETADDRINFO=1
CDEFINES += -DHAS_GETHOSTBYADDR_R=1
CDEFINES += -DHAS_GETHOSTBYNAME_R=1
CDEFINES += -DHAS_GETNAMEINFO=1
CDEFINES += -DHAS_INET_NTOP=1
CDEFINES += -DHAS_INET_PTON=1
CDEFINES += -DHAS_MSGHDR_FLAGS=1
CDEFINES += -DHAS_POLL=1
CDEFINES += -DHAS_SOCKLEN_T=1

CXXDEFINES += -D__STDC_CONSTANT_MACROS
#CXXDEFINES += -DHAVE_HIDAPI=1
#CXXDEFINES += -DUSE_UPNP
#CXXDEFINES += -D__LIBUSB__
#CXXDEFINES += -D__STDC_LIMIT_MACROS


# windows
DEFINES_win += -D_WIN32_WINNT=0x0602
DEFINES_win += -DWIN32_LEAN_AND_MEAN
DEFINES_win += -DNOMINMAX
DEFINES_win += -DCURL_STATICLIB
DEFINES_win += -DPSAPI_VERSION=1
DEFINES_win += -D_UNICODE
DEFINES_win += -DUNICODE
DEFINES_win += -D_CRT_SECURE_NO_WARNINGS
DEFINES_win += -D_CRT_SECURE_NO_DEPRECATE
DEFINES_win += -DUSE_USBDK

CXXDEFINES_win += -DSFML_STATIC
CXXDEFINES_win += -D_HAS_EXCEPTIONS=0
